# Tiền xử lý dữ liệu xuất khẩu nông sản Việt Nam (2017–2025)

Notebook này thực hiện quá trình làm sạch và chuẩn hóa dữ liệu xuất khẩu nông sản Việt Nam giai đoạn 2017–2025.

Các công việc chính bao gồm:

- Đọc dữ liệu từ các file Excel.
- Chuẩn hóa cấu trúc dữ liệu giữa các năm.
- Chuẩn hóa tên cột và tên mặt hàng.
- Lọc các mặt hàng nông sản phục vụ nghiên cứu.
- Xử lý kiểu dữ liệu.
- Ghép dữ liệu thành một bộ dữ liệu thống nhất.
- Lưu dữ liệu đã làm sạch để phục vụ phân tích và trực quan hóa.

## 1. Import các thư viện cần thiết

Sử dụng các thư viện phục vụ cho việc đọc, xử lý và lưu dữ liệu.

In [27]:
# Import modul
import pandas as pd
import numpy as np
import os
import glob
import re

In [28]:
# Đọc dữ liệu
filePath = "/run/media/a356/DATA/DEV/PYTHON/DATA VISUALIZATION/DATA_raw/V1-2018.xls"
df = pd.read_excel(filePath, header=None)
print(f"Kích thước dữ liệu: {df.shape}")
# Xem 10 dòng dữ liệu đầu   
df.head(10)

Kích thước dữ liệu: (59, 28)

,0,1,2,3,4,5,6,7,8,9,...,18,19,20,21,22,23,24,25,26,27
0,Trị giá và mặt hàng xuất khẩu sơ bộ các tháng ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Tên hàng,ĐVT,Tháng 01,NaN,Tháng 02,NaN,Tháng 03,NaN,Tháng 4,NaN,...,Tháng 9,NaN,Tháng 10,NaN,Tháng 11,NaN,Sơ bộ tháng 12,NaN,Sơ bộ năm 2018,NaN
3,NaN,NaN,Lượng,Trị giá \n(1000 USD),Lượng,Trị giá \n(1000 USD),Lượng,Trị giá \n(1000 USD),Lượng,Trị giá \n(1000 USD),...,Lượng,Trị giá \n(1000 USD),Lượng,Trị giá \n(1000 USD),Lượng,Trị giá \n(1000 USD),Lượng,Trị giá \n(1000 USD),Lượng,Trị giá \n(1000 USD)
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Tổng số,NaN,NaN,20220279.17,NaN,14289212.1,NaN,21053021.939,0,18327958.617,...,NaN,21053334.297,0,22558637.452,NaN,21697490.607,NaN,19759813.787,NaN,243483284.213
6,Trong đó:Khu vực có vốn ĐTTTNN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,...,NaN,0,0,0,NaN,0,NaN,0,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,...,NaN,0,0,0,NaN,0,NaN,0,NaN,NaN
8,Kể cả dầu thô,NaN,NaN,14321459.689,NaN,10577970.542,NaN,15374503.119,NaN,12794634.148,...,NaN,15524946.698,NaN,16395219.178,NaN,15818020.472,NaN,13229805.023,NaN,173722576.21
9,Không kể dầu thô,NaN,NaN,14116518.269,NaN,10415387.412,0,15231906.029,0,12675308.888,...,NaN,15359432.728,NaN,16173059.617,NaN,15646567.267,NaN,13083770.405,NaN,171532711.31

## 2. Xác định các mặt hàng nông sản nghiên cứu

Đề tài chỉ tập trung vào các mặt hàng nông sản chủ lực của Việt Nam, bao gồm:

- Thủy sản
- Rau quả
- Hạt điều
- Cà phê
- Chè
- Hạt tiêu
- Gạo
- Sắn và sản phẩm của sắn
- Cao su
- Xơ, sợi dệt các loại

In [29]:
for i in range(10): 
    print(f"Dòng {i}")
    print(df.iloc[i].tolist())

Dòng 0
['Trị giá và mặt hàng xuất khẩu sơ bộ các tháng năm 2018', nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
Dòng 1
[nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
Dòng 2
['Tên hàng', 'ĐVT', 'Tháng 01', nan, 'Tháng 02', nan, 'Tháng 03', nan, 'Tháng 4', nan, 'Tháng 5', nan, 'Tháng 6', nan, 'Tháng 7', nan, 'Tháng 8', nan, 'Tháng 9', nan, 'Tháng 10', nan, 'Tháng 11', nan, 'Sơ bộ tháng 12', nan, 'Sơ bộ năm 2018', nan]
Dòng 3
[nan, nan, 'Lượng', 'Trị giá \n(1000 USD)', 'Lượng', 'Trị giá \n(1000 USD)', 'Lượng', 'Trị giá \n(1000 USD)', 'Lượng', 'Trị giá \n(1000 USD)', 'Lượng', 'Trị giá \n(1000 USD)', 'Lượng', 'Trị giá \n(1000 USD)', 'Lượng', 'Trị giá \n(1000 USD)', 'Lượng', 'Trị giá \n(1000 USD)', 'Lượng', 'Trị giá \n(1000 USD)', 'Lượng', 'Trị giá \n(1000 USD)', 'Lượng', 'Trị giá \n(1000 USD)', 'Lượng', 'Trị giá \n(1000 USD)', 'Lượng', 'Trị giá \n(1000 USD)']
Dòng 4
[nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
Dòng 5
['Tổng số', nan, nan, 20220279.17, nan, 14289212.100000001, nan, 21053021.938999996, 0, 18327958.617000006, nan, 20438916.81799999, nan, 19860099.383, nan, 20321357.292000003, nan, 23903162.750999987, nan, 21053334.29700002, 0, 22558637.451999992, nan, 21697490.606999993, nan, 19759813.787, nan, 243483284.213]
Dòng 6
['Trong đó:Khu vực có vốn ĐTTTNN', nan, nan, nan, nan, nan, nan, nan, 0, nan, nan, 0, nan, 0, nan, 0, nan, 0, nan, 0, 0, 0, nan, 0, nan, 0, nan, nan]
Dòng 7
[nan, nan, nan, nan, nan, nan, nan, nan, 0, nan, nan, 0, nan, 0, nan, 0, nan, 0, nan, 0, 0, 0, nan, 0, nan, 0, nan, nan]
Dòng 8
['Kể cả dầu thô', nan, nan, 14321459.689, nan, 10577970.542000003, nan, 15374503.119, nan, 12794634.147999996, nan, 14109481.519000005, nan, 13830765.504999999, nan, 14434908.197000002, nan, 17277929.184, nan, 15524946.698, nan, 16395219.178000018, nan, 15818020.472000003, nan, 13229805.023000002, nan, 173722576.21]
Dòng 9
['Không kể dầu thô', nan, nan, 14116518.269, nan, 10415387.412000002, 0, 15231906.029000001, 0, 12675308.887999997, nan, 13899244.219000004, nan, 13622637.844999999, nan, 14234014.777000003, nan, 17074863.854000002, nan, 15359432.728, nan, 16173059.617000014, nan, 15646567.26699999, nan, 13083770.405000001, nan, 171532711.31]

In [30]:
# Fill lại các ô nan ở tỉêu đề cho dòng header
header1 = df.iloc[2].ffill()
header2 = df.iloc[3]
print(header1)

0           Tên hàng
1                ĐVT
2           Tháng 01
3           Tháng 01
4           Tháng 02
5           Tháng 02
6           Tháng 03
7           Tháng 03
8            Tháng 4
9            Tháng 4
10           Tháng 5
11           Tháng 5
12           Tháng 6
13           Tháng 6
14           Tháng 7
15           Tháng 7
16           Tháng 8
17           Tháng 8
18           Tháng 9
19           Tháng 9
20          Tháng 10
21          Tháng 10
22          Tháng 11
23          Tháng 11
24    Sơ bộ tháng 12
25    Sơ bộ tháng 12
26    Sơ bộ năm 2018
27    Sơ bộ năm 2018
Name: 2, dtype: object

In [31]:
# Ghép 2 header, viết lại headerheader
columns = []
for h1, h2 in zip(header1, header2):
    h1 = "" if pd.isna(h1) else str(h1).strip()
    h2 = "" if pd.isna(h2) else str(h2).strip()
    if h2 == "":
        columns.append(h1)
    else: 
        columns.append(f"{h1}_{h2}")
print(columns)

['Tên hàng', 'ĐVT', 'Tháng 01_Lượng', 'Tháng 01_Trị giá \n(1000 USD)', 'Tháng 02_Lượng', 'Tháng 02_Trị giá \n(1000 USD)', 'Tháng 03_Lượng', 'Tháng 03_Trị giá \n(1000 USD)', 'Tháng 4_Lượng', 'Tháng 4_Trị giá \n(1000 USD)', 'Tháng 5_Lượng', 'Tháng 5_Trị giá \n(1000 USD)', 'Tháng 6_Lượng', 'Tháng 6_Trị giá \n(1000 USD)', 'Tháng 7_Lượng', 'Tháng 7_Trị giá \n(1000 USD)', 'Tháng 8_Lượng', 'Tháng 8_Trị giá \n(1000 USD)', 'Tháng 9_Lượng', 'Tháng 9_Trị giá \n(1000 USD)', 'Tháng 10_Lượng', 'Tháng 10_Trị giá \n(1000 USD)', 'Tháng 11_Lượng', 'Tháng 11_Trị giá \n(1000 USD)', 'Sơ bộ tháng 12_Lượng', 'Sơ bộ tháng 12_Trị giá \n(1000 USD)', 'Sơ bộ năm 2018_Lượng', 'Sơ bộ năm 2018_Trị giá \n(1000 USD)']

In [32]:
# Reset lại header
df = df.iloc[5:].reset_index(drop=True)
# Đặt lại tên cột
df.columns = columns
df.head(20)
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 54 entries, 0 to 53
Data columns (total 28 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Tên hàng                            53 non-null     str
 1   ĐVT                                 48 non-null     str
 2   Tháng 01_Lượng                      16 non-null     object
 3   Tháng 01_Trị giá
(1000 USD)        51 non-null     object
 4   Tháng 02_Lượng                      48 non-null     object
 5   Tháng 02_Trị giá
(1000 USD)        52 non-null     object
 6   Tháng 03_Lượng                      50 non-null     object
 7   Tháng 03_Trị giá
(1000 USD)        52 non-null     object
 8   Tháng 4_Lượng                       53 non-null     object
 9   Tháng 4_Trị giá
(1000 USD)         51 non-null     object
 10  Tháng 5_Lượng                       48 non-null     object
 11  Tháng 5_Trị giá
(1000 USD)         54 non-null     object
 12  Tháng 6_Lượng                       46 non-null     object
 13  Tháng 6_Trị giá
(1000 USD)         54 non-null     object
 14  Tháng 7_Lượng                       46 non-null     object
 15  Tháng 7_Trị giá
(1000 USD)         54 non-null     object
 16  Tháng 8_Lượng                       46 non-null     object
 17  Tháng 8_Trị giá
(1000 USD)         53 non-null     object
 18  Tháng 9_Lượng                       46 non-null     object
 19  Tháng 9_Trị giá
(1000 USD)         54 non-null     object
 20  Tháng 10_Lượng                      49 non-null     object
 21  Tháng 10_Trị giá
(1000 USD)        54 non-null     object
 22  Tháng 11_Lượng                      46 non-null     object
 23  Tháng 11_Trị giá
(1000 USD)        54 non-null     object
 24  Sơ bộ tháng 12_Lượng                46 non-null     object
 25  Sơ bộ tháng 12_Trị giá
(1000 USD)  54 non-null     object
 26  Sơ bộ năm 2018_Lượng                16 non-null     object
 27  Sơ bộ năm 2018_Trị giá
(1000 USD)  51 non-null     object
dtypes: object(26), str(2)
memory usage: 11.9+ KB
None

In [33]:
# Liệt kê các hàng trong cột
df.iloc[:, 1].dropna().unique()

<StringArray>
['1000 USD', '"', 'Tấn']
Length: 3, dtype: str

In [34]:
# Liệt kê các hàng cần xóa
keywords = [
    "Thủy sản",
    "Rau",
    "điều",
    "Cà phê",
    "Chè",
    "tiêu",
    "Gạo",
    "Sắn",
    "Cao su",
    "Xơ"
]
df.iloc[:, 1] = df.iloc[:, 1].astype(str).str.strip()
df = df[
    df.iloc[:, 1].apply(lambda x: any(keyword.lower() in str(x).lower() for keyword in keywords))
]
df.head(30)

Empty DataFrame
Columns: [Tên hàng, ĐVT, Tháng 01_Lượng, Tháng 01_Trị giá
(1000 USD), Tháng 02_Lượng, Tháng 02_Trị giá
(1000 USD), Tháng 03_Lượng, Tháng 03_Trị giá
(1000 USD), Tháng 4_Lượng, Tháng 4_Trị giá
(1000 USD), Tháng 5_Lượng, Tháng 5_Trị giá
(1000 USD), Tháng 6_Lượng, Tháng 6_Trị giá
(1000 USD), Tháng 7_Lượng, Tháng 7_Trị giá
(1000 USD), Tháng 8_Lượng, Tháng 8_Trị giá
(1000 USD), Tháng 9_Lượng, Tháng 9_Trị giá
(1000 USD), Tháng 10_Lượng, Tháng 10_Trị giá
(1000 USD), Tháng 11_Lượng, Tháng 11_Trị giá
(1000 USD), Sơ bộ tháng 12_Lượng, Sơ bộ tháng 12_Trị giá
(1000 USD), Sơ bộ năm 2018_Lượng, Sơ bộ năm 2018_Trị giá
(1000 USD)]
Index: []

[0 rows x 28 columns]

In [35]:
# Chuẩn hóa tên hàng 
mapping = {
    # Thủy sản
    "thủy sản": "Thủy sản",
    "hàng hải sản": "Thủy sản",

    # Rau quả
    "rau quả": "Rau quả",
    "hàng rau quả": "Rau quả",

    # Các mặt hàng giữ nguyên
    "hạt điều": "Hạt điều",
    "cà phê": "Cà phê",
    "chè": "Chè",
    "hạt tiêu": "Hạt tiêu",
    "gạo": "Gạo",
    "cao su": "Cao su",

    # Sắn
    "sắn và sản phẩm của sắn": "Sắn và sản phẩm của sắn",
    "sắn và các sản phẩm từ sắn": "Sắn và sản phẩm của sắn",

    # Xơ
    "xơ, sợi dệt": "Xơ, sợi dệt các loại",
    "xơ, sợi dệt các loại": "Xơ, sợi dệt các loại",
}
# Hàm chuẩn hóahóa
def normalize_item(item):
    item = str(item).strip().lower()
    return mapping.get(item, item.title())

## 4. Chuẩn hóa tên cột

Các báo cáo của từng năm có sự khác nhau về tên cột như:

- Tháng 01 và Tháng 1
- Sơ bộ tháng 12
- Sơ bộ năm 2024
- 12 tháng
- Trị giá (1000 USD)

Các tên cột được chuẩn hóa nhằm đảm bảo tất cả các năm có cùng cấu trúc dữ liệu.

In [36]:
# Chuẩn hóa tên cột
def standardize_columns(columns):
    new_columns = []
    for col in columns:
        # NaN
        if pd.isna(col):
            new_columns.append("")
            continue
        col = str(col)
        # Xóa khoảng trắng và xuống dòng
        col = col.replace("\n", " ")
        col = " ".join(col.split())
        # Xóa đơn vị
        col = re.sub(r"\(.*?\)", "", col).strip()
        # STT
        col = col.replace("Stt", "STT")
        # Chuẩn hóa tháng
        col = re.sub(r"Tháng\s*0([1-9])", r"Tháng \1", col)
        # Bỏ chữ "Sơ bộ"
        col = col.replace("Sơ bộ tháng", "Tháng")
        col = re.sub(r"Sơ bộ năm\s+\d{4}", "Cả năm", col)
        # Chuẩn hóa "12 tháng", "cả năm"
        col = col.replace("12 tháng", "Cả năm")
        col = col.replace("cả năm", "Cả năm")
        # Bỏ chữ "Sơ bộ" còn sót
        col = col.replace("Sơ bộ", "").strip()
        # Chuẩn hóa trị giá
        col = col.replace("Trị giá 1000 USD", "Trị giá")
        col = col.replace("Trị giá USD", "Trị giá")
        new_columns.append(col)
    return new_columns

## 5. Xây dựng hàm làm sạch dữ liệu

Hàm `clean_file()` thực hiện các bước:

1. Đọc file Excel.
2. Tự động xác định vị trí header.
3. Ghép hai dòng tiêu đề.
4. Chuẩn hóa tên cột.
5. Loại bỏ các cột không cần thiết.
6. Chuẩn hóa tên mặt hàng.
7. Lọc các mặt hàng thuộc phạm vi nghiên cứu.
8. Thêm thông tin năm.

In [37]:
# Xử lí file
keywords = [
    "Thủy sản",
    "Rau quả",
    "Hạt điều",
    "Cà phê",
    "Chè",
    "Hạt tiêu",
    "Gạo",
    "Sắn và sản phẩm của sắn",
    "Cao su",
    "Xơ, sợi dệt các loại"
]
def clean_file(filePath):
    # Đọc file
    df = pd.read_excel(filePath, header=None)
    # Tìm dòng header
    header_row = None
    for i in range(10):
        row = df.iloc[i].astype(str)
        if row.str.contains("Tên hàng|Stt", case=False, na=False).any():
            header_row = i
            break
    if header_row is None:
        raise ValueError(f"Không tìm thấy header trong file: {filePath}")
    # Ghép header
    header1 = df.iloc[header_row].ffill()
    header2 = df.iloc[header_row + 1]
    columns = []
    for h1, h2 in zip(header1, header2):
        h1 = "" if pd.isna(h1) else str(h1).strip()
        h2 = "" if pd.isna(h2) else str(h2).strip()
        if h2 == "":
            columns.append(h1)
        else:
            columns.append(f"{h1}_{h2}")
    # Chuẩn hóa tên cột
    columns = standardize_columns(columns)
    # File 2017 cột thứ 2 đang để trống
    if len(columns) > 1 and columns[1] == "":
        columns[1] = "Tên hàng"
    # Lấy phần dữ liệu
    df = df.iloc[header_row + 3:].reset_index(drop=True)
    # Gán tên cột
    df.columns = columns
    # Xóa các cột không cần
    drop_cols = [
    "STT",
    "",
    "ĐVT",
    "Cả năm_Lượng",
    "Cả năm_Trị giá",
    "12 Tháng_Lượng",
    "12 Tháng_Trị giá"  
    ]
    df = df.drop(
        columns=[c for c in drop_cols if c in df.columns],
        errors="ignore"
    )
    # Chuẩn hóa tên mặt hàng
    item_col = "Tên hàng"
    df[item_col] = (
        df[item_col]
        .astype(str)
        .str.strip() 
        .apply(normalize_item)
    )
    # Chỉ giữ mặt hàng nông sản
    df = df[df[item_col].isin(keywords)].reset_index(drop=True)
    return df

## 6. Đọc dữ liệu các năm

Dữ liệu từ năm 2017 đến năm 2025 được đọc tự động bằng vòng lặp và xử lý thông qua hàm `clean_file()`.

In [48]:
# Lưu lại các đường dẫn 
df_full = [] 
for year in range(2017, 2026):
    filePaths = f"/run/media/a356/DATA/DEV/PYTHON/DATA VISUALIZATION/DATA_raw/V1-{year}.xls"
    df = clean_file(filePaths)
    df["Year"] = year
    print(year, df.shape)
    df_full.append(df)
#Ghép tất cả các file lại thành một frameframe
df_full = pd.concat(df_full, ignore_index=True)
# Chuyển đơn vị tinh năm 2017 từ triệu USD về nghìn USD và từ nghìn tấn về tấn 
quantity_cols = [
    col for col in df_full.columns
    if "Lượng" in col
]
df_full.loc[df_full["Year"] == 2017, quantity_cols] *= 1000

value_cols = [
    col for col in df_full.columns
    if "Trị giá" in col
]
df_full.loc[df_full["Year"] == 2017, value_cols] *= 1000
df_full.head(10)

2017 (10, 26)
2018 (10, 26)
2019 (10, 26)
2020 (10, 26)
2021 (10, 26)
2022 (10, 26)
2023 (10, 26)
2024 (10, 26)
2025 (10, 26)

,Tên hàng,Tháng 1_Lượng,Tháng 1_Trị giá,Tháng 2_Lượng,Tháng 2_Trị giá,Tháng 3_Lượng,Tháng 3_Trị giá,Tháng 4_Lượng,Tháng 4_Trị giá,Tháng 5_Lượng,...,Tháng 8_Trị giá,Tháng 9_Lượng,Tháng 9_Trị giá,Tháng 10_Lượng,Tháng 10_Trị giá,Tháng 11_Lượng,Tháng 11_Trị giá,Tháng 12_Lượng,Tháng 12_Trị giá,Year
0,Thủy sản,0,485025.84,0,423000,0,600000,0,636000,0,...,838000,0,774000,0,855000,0,762000,0,742000,2017
1,Rau quả,0,236000,0,187000,0,280000,0,323000,0,...,322000,0,279000,0,240000,0,313971.665,0,323013.853,2017
2,Hạt điều,17846.0,163126.135,13327.0,121335.873,24121.0,228950.735,28277.0,272857.341,32920.0,...,377901.647,32871.0,330227.94,33179.0,331756.949,31856.0,323043.009,30260.0,308000,2017
3,Cà phê,184917.0,410455.012,167880.0,377679.231,186010.0,420978.874,143600.0,324899.949,127689.0,...,224953.653,79948.0,186419.987,79262.0,185105.838,104724.0,225107.334,163937.0,326571.931,2017
4,Chè,10000,13511.635,10000,14000,10414.0,14452.195,10000,15735.369,15000,...,23138.497,12000,20701.619,14000,24000,14000,23000,12000,20000,2017
5,Hạt tiêu,8312.0,61588.498,13671.0,90484.87,28928.0,169752.412,25112.0,142109.317,26497.0,...,91847.355,13424.0,64382.807,10987.0,50654.145,10587.0,49000,12502.0,53484.183,2017
6,Gạo,334249.0,142977.91,399197.0,169105.695,503413.0,226674.23,533574.0,249554.525,558898.0,...,280839.132,496913.0,227688.169,483029.0,245810.618,367615.0,176946.999,380640.0,181885.663,2017
7,Sắn và sản phẩm của sắn,NaN,59207.682,NaN,103934.832,NaN,128372.054,NaN,69965.37,NaN,...,69454.689,NaN,83006.127,NaN,88000,NaN,107027.637,NaN,122470.424,2017
8,Cao su,93223.0,179206.915,90237.0,191900.777,65718.0,137671.894,51389.0,96792.187,60239.0,...,261724.061,147373.0,236056.369,115838.0,177856.374,145429.0,213059.943,168628.0,243685.447,2017
9,"Xơ, sợi dệt các loại",78899.0,204326.094,101392.0,268418.627,114815.0,306946.816,NaN,287233.866,NaN,...,332371.689,NaN,320811.567,NaN,314309.797,NaN,321597.572,NaN,328000,2017

## 8. Kiểm tra kết quả

Thực hiện kiểm tra:

- Kích thước dữ liệu
- Kiểu dữ liệu
- Giá trị thiếu
- Giá trị trùng lặp
- Danh sách mặt hàng
- Danh sách các năm

In [39]:
print(f"Kích thước dữ liệu {df.shape}")

Kích thước dữ liệu (10, 26)

In [40]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 26 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Tên hàng          10 non-null     str
 1   Tháng 1_Lượng     8 non-null      object
 2   Tháng 1_Trị giá   10 non-null     object
 3   Tháng 2_Lượng     10 non-null     object
 4   Tháng 2_Trị giá   10 non-null     object
 5   Tháng 3_Lượng     10 non-null     object
 6   Tháng 3_Trị giá   10 non-null     object
 7   Tháng 4_Lượng     10 non-null     object
 8   Tháng 4_Trị giá   10 non-null     object
 9   Tháng 5_Lượng     10 non-null     object
 10  Tháng 5_Trị giá   10 non-null     object
 11  Tháng 6_Lượng     10 non-null     object
 12  Tháng 6_Trị giá   10 non-null     object
 13  Tháng 7_Lượng     10 non-null     object
 14  Tháng 7_Trị giá   10 non-null     object
 15  Tháng 8_Lượng     10 non-null     object
 16  Tháng 8_Trị giá   10 non-null     object
 17  Tháng 9_Lượng     10 non-null     object
 18  Tháng 9_Trị giá   10 non-null     object
 19  Tháng 10_Lượng    10 non-null     object
 20  Tháng 10_Trị giá  10 non-null     object
 21  Tháng 11_Lượng    10 non-null     object
 22  Tháng 11_Trị giá  10 non-null     object
 23  Tháng 12_Lượng    8 non-null      object
 24  Tháng 12_Trị giá  10 non-null     object
 25  Year              10 non-null     int64
dtypes: int64(1), object(24), str(1)
memory usage: 2.2+ KB

In [41]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 26 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Tên hàng          10 non-null     str
 1   Tháng 1_Lượng     8 non-null      object
 2   Tháng 1_Trị giá   10 non-null     object
 3   Tháng 2_Lượng     10 non-null     object
 4   Tháng 2_Trị giá   10 non-null     object
 5   Tháng 3_Lượng     10 non-null     object
 6   Tháng 3_Trị giá   10 non-null     object
 7   Tháng 4_Lượng     10 non-null     object
 8   Tháng 4_Trị giá   10 non-null     object
 9   Tháng 5_Lượng     10 non-null     object
 10  Tháng 5_Trị giá   10 non-null     object
 11  Tháng 6_Lượng     10 non-null     object
 12  Tháng 6_Trị giá   10 non-null     object
 13  Tháng 7_Lượng     10 non-null     object
 14  Tháng 7_Trị giá   10 non-null     object
 15  Tháng 8_Lượng     10 non-null     object
 16  Tháng 8_Trị giá   10 non-null     object
 17  Tháng 9_Lượng     10 non-null     object
 18  Tháng 9_Trị giá   10 non-null     object
 19  Tháng 10_Lượng    10 non-null     object
 20  Tháng 10_Trị giá  10 non-null     object
 21  Tháng 11_Lượng    10 non-null     object
 22  Tháng 11_Trị giá  10 non-null     object
 23  Tháng 12_Lượng    8 non-null      object
 24  Tháng 12_Trị giá  10 non-null     object
 25  Year              10 non-null     int64
dtypes: int64(1), object(24), str(1)
memory usage: 2.2+ KB

In [42]:
# Kiểm tra giá trị trùng lặp
print(f"Số dòng bị trùng lặp {df.duplicated()}")

Số dòng bị trùng lặp 0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

In [43]:
print(df_full.groupby("Year")["Tên hàng"].sum().value_counts())

Tên hàng
Thủy sảnRau quảHạt điềuCà phêChèHạt tiêuGạoSắn và sản phẩm của sắnCao suXơ, sợi dệt các loại    9
Name: count, dtype: int64

In [44]:
# Kiểm tra mặt hàng thiếu 
missing_rows = df[df.isna().any(axis=1)]
print(
    missing_rows[
        ["Tên hàng", "Year"]
    ]
)

   Tên hàng  Year
0  Thủy sản  2025
1   Rau quả  2025

In [45]:
for idx, row in df[df.isna().any(axis=1)].iterrows():
    missing_cols = row[row.isna()].index.tolist()

    print(
        f"Năm: {row['Year']} | "
        f"Mặt hàng: {row['Tên hàng']}"
    )
    print("Thiếu:", missing_cols)
    print()

Năm: 2025 | Mặt hàng: Thủy sản
Thiếu: ['Tháng 1_Lượng', 'Tháng 12_Lượng']

Năm: 2025 | Mặt hàng: Rau quả
Thiếu: ['Tháng 1_Lượng', 'Tháng 12_Lượng']

In [46]:
print("Kích thước dữ liệu raw:", df.shape)
display(df.head())
print("Kích thước sau khi clean:", df_full.shape)
display(df_full.head())
print("Missing:")
print(df_full.isnull().sum())
print("Duplicate:", df_full.duplicated().sum())

Kích thước dữ liệu raw: (10, 26)

,Tên hàng,Tháng 1_Lượng,Tháng 1_Trị giá,Tháng 2_Lượng,Tháng 2_Trị giá,Tháng 3_Lượng,Tháng 3_Trị giá,Tháng 4_Lượng,Tháng 4_Trị giá,Tháng 5_Lượng,...,Tháng 8_Trị giá,Tháng 9_Lượng,Tháng 9_Trị giá,Tháng 10_Lượng,Tháng 10_Trị giá,Tháng 11_Lượng,Tháng 11_Trị giá,Tháng 12_Lượng,Tháng 12_Trị giá,Year
0,Thủy sản,NaN,773870.841,0,654352.174,0,881915.078,0,900283.937,0,...,1073618.091,0,1012815.024,0,1158318.061,0,1004734.826,NaN,954308.875,2025
1,Rau quả,NaN,372926.617,0,313437.415,0,476753.346,0,521860.03,0,...,950361.395,0,1311122.75,0,927834.918,0,710928.577,NaN,793756.659,2025
2,Hạt điều,37364,255747.702,28968,199131.132,55863,384498.428,73450,494237.271,81065,...,472879.135,72550,491730.417,73321,504827.649,70342,485368.926,68061,465597.58,2025
3,Cà phê,134005,756830.158,180660,990535.679,184618,1082493.378,175863,1014314.616,153973,...,509022.893,83379,473316.535,71176,406847.18,96150,546860.223,182967,947992.767,2025
4,Chè,9699,16397.041,7639,11919.871,9523,14715.573,8828,14807.111,10770,...,25068.793,12270,21530.65,12101,21344.485,13780,25400.907,13844,23887.645,2025

Kích thước sau khi clean: (90, 26)

,Tên hàng,Tháng 1_Lượng,Tháng 1_Trị giá,Tháng 2_Lượng,Tháng 2_Trị giá,Tháng 3_Lượng,Tháng 3_Trị giá,Tháng 4_Lượng,Tháng 4_Trị giá,Tháng 5_Lượng,...,Tháng 8_Trị giá,Tháng 9_Lượng,Tháng 9_Trị giá,Tháng 10_Lượng,Tháng 10_Trị giá,Tháng 11_Lượng,Tháng 11_Trị giá,Tháng 12_Lượng,Tháng 12_Trị giá,Year
0,Thủy sản,0,485025.84,0,423000,0,600000,0,636000,0,...,838000,0,774000,0,855000,0,762000,0,742000,2017
1,Rau quả,0,236000,0,187000,0,280000,0,323000,0,...,322000,0,279000,0,240000,0,313971.665,0,323013.853,2017
2,Hạt điều,17846.0,163126.135,13327.0,121335.873,24121.0,228950.735,28277.0,272857.341,32920.0,...,377901.647,32871.0,330227.94,33179.0,331756.949,31856.0,323043.009,30260.0,308000,2017
3,Cà phê,184917.0,410455.012,167880.0,377679.231,186010.0,420978.874,143600.0,324899.949,127689.0,...,224953.653,79948.0,186419.987,79262.0,185105.838,104724.0,225107.334,163937.0,326571.931,2017
4,Chè,10000,13511.635,10000,14000,10414.0,14452.195,10000,15735.369,15000,...,23138.497,12000,20701.619,14000,24000,14000,23000,12000,20000,2017

Missing:
Tên hàng             0
Tháng 1_Lượng       17
Tháng 1_Trị giá      0
Tháng 2_Lượng        2
Tháng 2_Trị giá      0
Tháng 3_Lượng        1
Tháng 3_Trị giá      0
Tháng 4_Lượng        2
Tháng 4_Trị giá      0
Tháng 5_Lượng        2
Tháng 5_Trị giá      0
Tháng 6_Lượng        4
Tháng 6_Trị giá      0
Tháng 7_Lượng        4
Tháng 7_Trị giá      0
Tháng 8_Lượng        4
Tháng 8_Trị giá      0
Tháng 9_Lượng        6
Tháng 9_Trị giá      0
Tháng 10_Lượng       4
Tháng 10_Trị giá     0
Tháng 11_Lượng       4
Tháng 11_Trị giá     0
Tháng 12_Lượng       8
Tháng 12_Trị giá     0
Year                 0
dtype: int64
Duplicate: 0

# Lưu trữ dữ liệu sạch dưới file excel

In [47]:
output_path = "/run/media/a356/DATA/DEV/PYTHON/DATA VISUALIZATION/DATA_processed/Du_lieu_xuat_khau_nong_san.xlsx"
os.makedirs(os.path.dirname(output_path), exist_ok=True)
df_full.to_excel(output_path, index=False)