# Phân tích khám phá dữ liệu (EDA)

Notebook này thực hiện phân tích khám phá dữ liệu xuất khẩu các mặt hàng nông sản
Việt Nam trong giai đoạn 2017–2025.

1. Mục tiêu:
- Kiểm tra chất lượng dữ liệu sau tiền xử lý.
- Khảo sát đặc điểm của dữ liệu.
- Phân tích tình hình xuất khẩu theo năm, tháng và mặt hàng.
- Tìm ra các xu hướng và đặc điểm nổi bật trong dữ liệu.

In [176]:
import pandas as pd
import numpy as np
import os
import glob
import seaborn as sns
import matplotlib.pyplot as plt

# 2. Đọc dữ liệu

In [177]:
# Đọc file
filePath = "/run/media/a356/DATA/DEV/PYTHON/DATA VISUALIZATION/DATA_processed/Du_lieu_xuat_khau_nong_san.xlsx"
df = pd.read_excel(filePath)
print(f"Kích thước dữ liệu {df.shape}")
df.head(5)

Kích thước dữ liệu (90, 26)

,Tên hàng,Tháng 1_Lượng,Tháng 1_Trị giá,Tháng 2_Lượng,Tháng 2_Trị giá,Tháng 3_Lượng,Tháng 3_Trị giá,Tháng 4_Lượng,Tháng 4_Trị giá,Tháng 5_Lượng,...,Tháng 8_Trị giá,Tháng 9_Lượng,Tháng 9_Trị giá,Tháng 10_Lượng,Tháng 10_Trị giá,Tháng 11_Lượng,Tháng 11_Trị giá,Tháng 12_Lượng,Tháng 12_Trị giá,Year
0,Thủy sản,0.0,485025.840,0.0,423000.000,0.0,600000.000,0.0,636000.000,0.0,...,838000.000,0.0,774000.000,0.0,855000.000,0.0,762000.000,0.0,742000.000,2017
1,Rau quả,0.0,236000.000,0.0,187000.000,0.0,280000.000,0.0,323000.000,0.0,...,322000.000,0.0,279000.000,0.0,240000.000,0.0,313971.665,0.0,323013.853,2017
2,Hạt điều,17846.0,163126.135,13327.0,121335.873,24121.0,228950.735,28277.0,272857.341,32920.0,...,377901.647,32871.0,330227.940,33179.0,331756.949,31856.0,323043.009,30260.0,308000.000,2017
3,Cà phê,184917.0,410455.012,167880.0,377679.231,186010.0,420978.874,143600.0,324899.949,127689.0,...,224953.653,79948.0,186419.987,79262.0,185105.838,104724.0,225107.334,163937.0,326571.931,2017
4,Chè,10000.0,13511.635,10000.0,14000.000,10414.0,14452.195,10000.0,15735.369,15000.0,...,23138.497,12000.0,20701.619,14000.0,24000.000,14000.0,23000.000,12000.0,20000.000,2017

In [178]:
df.tail(5)

,Tên hàng,Tháng 1_Lượng,Tháng 1_Trị giá,Tháng 2_Lượng,Tháng 2_Trị giá,Tháng 3_Lượng,Tháng 3_Trị giá,Tháng 4_Lượng,Tháng 4_Trị giá,Tháng 5_Lượng,...,Tháng 8_Trị giá,Tháng 9_Lượng,Tháng 9_Trị giá,Tháng 10_Lượng,Tháng 10_Trị giá,Tháng 11_Lượng,Tháng 11_Trị giá,Tháng 12_Lượng,Tháng 12_Trị giá,Year
85,Hạt tiêu,12958.0,87277.558,14247.0,96843.428,20014.0,140108.486,26375.0,183926.919,26304.0,...,140239.261,20343.0,135816.523,18788.0,125981.656,18888.0,124196.273,22015.0,145020.675,2025
86,Gạo,547408.0,316429.942,682959.0,358256.898,1078404.0,530340.189,1115093.0,558252.184,775490.0,...,428273.216,463225.0,230151.088,339234.0,176905.005,380194.0,194161.016,522387.0,248769.533,2025
87,Sắn và sản phẩm của sắn,295909.0,99176.290,427863.0,134514.389,487675.0,139192.774,390979.0,112770.669,387254.0,...,101724.354,269948.0,89416.395,260258.0,88512.447,275298.0,97348.875,373219.0,135173.201,2025
88,Cao su,160632.0,298649.243,114613.0,224010.269,105393.0,210670.128,72129.0,140042.054,97171.0,...,359254.119,175560.0,301916.104,179779.0,304621.704,197033.0,335873.325,238663.0,404902.493,2025
89,"Xơ, sợi dệt các loại",131358.0,301099.955,153009.0,347011.063,174071.0,384670.992,161743.0,361092.876,154989.0,...,380370.900,163148.0,355847.874,168237.0,360272.316,166469.0,355185.771,190147.0,411098.030,2025

# 3. Kiểm tra dữ liệu
Mục tiêu của bước này là kiểm tra cấu trúc và chất lượng của bộ dữ liệu sau khi đã được tiền xử lý, bao gồm:
- Kích thước dữ liệu
- Kiểu dữ liệu
- Giá trị khuyết
- Dữ liệu trùng lặp
- Các năm trong bộ dữ liệu
- Các mặt hàng được phân tích
- Số lượng mặt hàng theo từng năm

In [179]:
# Kích thước
print(f"Số dòng {df.shape[0]}")
print(f"Số cột {df.shape[1]}")

Số dòng 90
Số cột 26

In [180]:
# Thông tin cột 
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 26 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Tên hàng          90 non-null     str
 1   Tháng 1_Lượng     73 non-null     float64
 2   Tháng 1_Trị giá   90 non-null     float64
 3   Tháng 2_Lượng     88 non-null     float64
 4   Tháng 2_Trị giá   90 non-null     float64
 5   Tháng 3_Lượng     89 non-null     float64
 6   Tháng 3_Trị giá   90 non-null     float64
 7   Tháng 4_Lượng     88 non-null     float64
 8   Tháng 4_Trị giá   90 non-null     float64
 9   Tháng 5_Lượng     88 non-null     float64
 10  Tháng 5_Trị giá   90 non-null     float64
 11  Tháng 6_Lượng     86 non-null     float64
 12  Tháng 6_Trị giá   90 non-null     float64
 13  Tháng 7_Lượng     86 non-null     float64
 14  Tháng 7_Trị giá   90 non-null     float64
 15  Tháng 8_Lượng     86 non-null     float64
 16  Tháng 8_Trị giá   90 non-null     float64
 17  Tháng 9_Lượng     84 non-null     float64
 18  Tháng 9_Trị giá   90 non-null     float64
 19  Tháng 10_Lượng    86 non-null     float64
 20  Tháng 10_Trị giá  90 non-null     float64
 21  Tháng 11_Lượng    86 non-null     float64
 22  Tháng 11_Trị giá  90 non-null     float64
 23  Tháng 12_Lượng    82 non-null     float64
 24  Tháng 12_Trị giá  90 non-null     float64
 25  Year              90 non-null     int64
dtypes: float64(24), int64(1), str(1)
memory usage: 18.4 KB

In [181]:
# Kiểm tra giá trị khuyết 
missing = df.isnull().sum()
print("Cột             Số lượng")
print(missing[missing > 0])

Cột             Số lượng
Tháng 1_Lượng     17
Tháng 2_Lượng      2
Tháng 3_Lượng      1
Tháng 4_Lượng      2
Tháng 5_Lượng      2
Tháng 6_Lượng      4
Tháng 7_Lượng      4
Tháng 8_Lượng      4
Tháng 9_Lượng      6
Tháng 10_Lượng     4
Tháng 11_Lượng     4
Tháng 12_Lượng     8
dtype: int64

In [182]:
# Kiểm tra giá trị trùng 
dup = df.duplicated().sum()
print(f"Số dòng bị trùng lặp {dup}")

Số dòng bị trùng lặp 0

In [183]:
# Thời gian dữ liệu
print("Các năm:")
print(sorted(df["Year"].unique().tolist()))

Các năm:
[2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025]

In [184]:
# Mặt hàng 
print("Mặt hàng:")
print(df["Tên hàng"].sort_values().unique().tolist())

Mặt hàng:
['Cao su', 'Chè', 'Cà phê', 'Gạo', 'Hạt tiêu', 'Hạt điều', 'Rau quả', 'Sắn và sản phẩm của sắn', 'Thủy sản', 'Xơ, sợi dệt các loại']

In [185]:
# Số mặt hàng mỗi năm
items_by_year = (
    df.groupby("Year")["Tên hàng"]
    .nunique().tolist()
)
print(items_by_year)

[10, 10, 10, 10, 10, 10, 10, 10, 10]

## 4. Thống kê mô tả

### 4.1 Thống kê mô tả dữ liệu Lượng
### 4.2 Thống kê mô tả dữ liệu Trị giá

In [186]:
# Thông kê lượng    
quantity_columns = [
    col for col in df.columns 
    if "Lượng" in col 
    ]
df[quantity_columns].describe()

,Tháng 1_Lượng,Tháng 2_Lượng,Tháng 3_Lượng,Tháng 4_Lượng,Tháng 5_Lượng,Tháng 6_Lượng,Tháng 7_Lượng,Tháng 8_Lượng,Tháng 9_Lượng,Tháng 10_Lượng,Tháng 11_Lượng,Tháng 12_Lượng
count,73.000000,88.000000,8.900000e+01,8.800000e+01,88.000000,86.000000,86.000000,86.000000,84.000000,86.000000,86.000000,82.000000
mean,152662.493151,113613.488636,1.583285e+05,1.455535e+05,141192.579545,125561.476744,132950.209302,146457.860465,125552.345238,126736.034884,130616.895349,151986.048780
std,151505.583580,151255.626700,2.335859e+05,2.376044e+05,219465.687732,161812.858549,177898.071695,210373.697373,164106.786507,166049.859761,154420.798780,160727.022682
min,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,17467.000000,6816.250000,9.277000e+03,9.465500e+03,9923.250000,12136.250000,13327.750000,13309.000000,13166.500000,13743.500000,12526.250000,13564.250000
50%,134005.000000,41953.000000,5.895400e+04,5.131150e+04,63899.500000,72546.000000,76798.500000,72770.500000,64804.500000,65000.000000,67323.500000,130006.000000
75%,210327.000000,154895.000000,1.860100e+05,1.584505e+05,147963.000000,152074.250000,167116.000000,178188.500000,169005.750000,181323.250000,208913.250000,235002.500000
max,547408.000000,682959.000000,1.106897e+06,1.115093e+06,984121.000000,724778.000000,788257.000000,918931.000000,818355.000000,793508.000000,699139.000000,583036.000000

In [187]:
# Thống kê trị giá 
value_columns = [
    col for col in df.columns 
    if "Lượng" in col 
    ]
df[value_columns].describe()

,Tháng 1_Lượng,Tháng 2_Lượng,Tháng 3_Lượng,Tháng 4_Lượng,Tháng 5_Lượng,Tháng 6_Lượng,Tháng 7_Lượng,Tháng 8_Lượng,Tháng 9_Lượng,Tháng 10_Lượng,Tháng 11_Lượng,Tháng 12_Lượng
count,73.000000,88.000000,8.900000e+01,8.800000e+01,88.000000,86.000000,86.000000,86.000000,84.000000,86.000000,86.000000,82.000000
mean,152662.493151,113613.488636,1.583285e+05,1.455535e+05,141192.579545,125561.476744,132950.209302,146457.860465,125552.345238,126736.034884,130616.895349,151986.048780
std,151505.583580,151255.626700,2.335859e+05,2.376044e+05,219465.687732,161812.858549,177898.071695,210373.697373,164106.786507,166049.859761,154420.798780,160727.022682
min,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,17467.000000,6816.250000,9.277000e+03,9.465500e+03,9923.250000,12136.250000,13327.750000,13309.000000,13166.500000,13743.500000,12526.250000,13564.250000
50%,134005.000000,41953.000000,5.895400e+04,5.131150e+04,63899.500000,72546.000000,76798.500000,72770.500000,64804.500000,65000.000000,67323.500000,130006.000000
75%,210327.000000,154895.000000,1.860100e+05,1.584505e+05,147963.000000,152074.250000,167116.000000,178188.500000,169005.750000,181323.250000,208913.250000,235002.500000
max,547408.000000,682959.000000,1.106897e+06,1.115093e+06,984121.000000,724778.000000,788257.000000,918931.000000,818355.000000,793508.000000,699139.000000,583036.000000

## 5. Phân tích theo năm

Phân tích sự thay đổi của lượng và trị giá xuất khẩu trong giai đoạn 2017–2025.

Mục tiêu:
- So sánh tổng lượng xuất khẩu giữa các năm.
- So sánh tổng trị giá xuất khẩu giữa các năm.
- Xác định năm có giá trị xuất khẩu cao nhất và thấp nhất.
- Quan sát xu hướng biến động qua thời gian.

In [188]:
# Tổng lượng xuất khẩu theo năm
quantity_cols = [
    col for col in df.columns
    if "Lượng" in col
]

quantity_by_year = (
    df.groupby("Year")[quantity_cols]
      .sum()
      .sum(axis=1)
)
print(quantity_by_year.map(lambda x: f"{x:,.0f} nghìn tấn"))

Year
2017     9,777,230 nghìn tấn
2018    14,196,495 nghìn tấn
2019    14,846,643 nghìn tấn
2020    15,045,676 nghìn tấn
2021    15,491,932 nghìn tấn
2022    16,746,805 nghìn tấn
2023    17,665,229 nghìn tấn
2024    18,006,009 nghìn tấn
2025    18,660,208 nghìn tấn
dtype: str

In [189]:
# Tổng trị giá xuất khẩu theo năm
value_cols = [
    col for col in df.columns
    if "Trị giá" in col
]
value_by_year = (
    df.groupby("Year")[value_cols]
      .sum()
      .sum(axis=1)
)
print(value_by_year.map(lambda x: f"{x:,.0f} nghìn USD"))

Year
2017    29,737,875 nghìn USD
2018    30,623,864 nghìn USD
2019    29,635,419 nghìn USD
2020    28,764,284 nghìn USD
2021    33,655,170 nghìn USD
2022    35,528,482 nghìn USD
2023    36,806,261 nghìn USD
2024    43,371,774 nghìn USD
2025    48,915,731 nghìn USD
dtype: str

In [190]:
# Năm xuất khẩu cao và thấp nhất
print("Năm có tổng sản lượng cao nhất:", quantity_by_year.idxmax())
print("Năm có tổng sản lượng thấp nhất:", quantity_by_year.idxmin())

print("Năm có tổng trị giá cao nhất:", value_by_year.idxmax())
print("Năm có tổng trị giá thấp nhất:", value_by_year.idxmin())

Năm có tổng sản lượng cao nhất: 2025
Năm có tổng sản lượng thấp nhất: 2017
Năm có tổng trị giá cao nhất: 2025
Năm có tổng trị giá thấp nhất: 2020

In [191]:
year_summary = pd.DataFrame({
    "Tổng sản lượng": quantity_by_year,
    "Tổng trị giá": value_by_year
})
year_summary_display = year_summary.copy()
year_summary_display["Tổng sản lượng"] = (
    year_summary_display["Tổng sản lượng"]
    .map(lambda x: f"{x:,.0f} nghìn tấn")
)
year_summary_display["Tổng trị giá"] = (
    year_summary_display["Tổng trị giá"]
    .map(lambda x: f"{x:,.0f} nghìn USD")
)
print(year_summary_display)

            Tổng sản lượng          Tổng trị giá
Year
2017   9,777,230 nghìn tấn  29,737,875 nghìn USD
2018  14,196,495 nghìn tấn  30,623,864 nghìn USD
2019  14,846,643 nghìn tấn  29,635,419 nghìn USD
2020  15,045,676 nghìn tấn  28,764,284 nghìn USD
2021  15,491,932 nghìn tấn  33,655,170 nghìn USD
2022  16,746,805 nghìn tấn  35,528,482 nghìn USD
2023  17,665,229 nghìn tấn  36,806,261 nghìn USD
2024  18,006,009 nghìn tấn  43,371,774 nghìn USD
2025  18,660,208 nghìn tấn  48,915,731 nghìn USD

## 6. Phân tích theo mặt hàng

Phân tích lượng và trị giá xuất khẩu của 10 nhóm mặt hàng nông sản
trong giai đoạn 2017–2025.

Mục tiêu:
- So sánh quy mô xuất khẩu giữa các mặt hàng.
- Xác định những mặt hàng có tổng lượng và tổng trị giá xuất khẩu cao nhất.
- Xác định những mặt hàng có đóng góp nổi bật trong tổng kim ngạch xuất khẩu.

In [192]:
# Tổng lượng theo mặt hàng
quantity_by_item = (
    df.groupby("Tên hàng")[quantity_cols]
      .sum()
      .sum(axis=1)
      .sort_values(ascending=False)
)
print(quantity_by_item.map(lambda x: f"{x:,.0f} nghìn tấn"))

Tên hàng
Gạo                        63,120,649 nghìn tấn
Sắn và sản phẩm của sắn    23,468,899 nghìn tấn
Cao su                     16,556,849 nghìn tấn
Cà phê                     14,563,615 nghìn tấn
Xơ, sợi dệt các loại       14,304,006 nghìn tấn
Hạt điều                    4,930,587 nghìn tấn
Hạt tiêu                    2,267,821 nghìn tấn
Chè                         1,223,801 nghìn tấn
Rau quả                             0 nghìn tấn
Thủy sản                            0 nghìn tấn
dtype: str

In [193]:
# Tổng lượng theo mặt hàng
value_by_item = (
    df.groupby("Tên hàng")[value_cols]
      .sum()
      .sum(axis=1)
      .sort_values(ascending=False)
)
print(value_by_item.map(lambda x: f"{x:,.0f} nghìn USD "))

Tên hàng
Thủy sản                   84,206,451 nghìn USD
Rau quả                    42,562,263 nghìn USD
Xơ, sợi dệt các loại       38,936,175 nghìn USD
Cà phê                     38,548,474 nghìn USD
Hạt điều                   33,323,826 nghìn USD
Gạo                        32,808,494 nghìn USD
Cao su                     25,262,095 nghìn USD
Sắn và sản phẩm của sắn    10,287,531 nghìn USD
Hạt tiêu                    9,046,165 nghìn USD
Chè                         2,057,386 nghìn USD
dtype: str

In [194]:
# Bảng tóm tắt tổng sản lượng và trị giá 
item_summary = pd.DataFrame({
    "Tổng sản lượng": quantity_by_item,
    "Tổng trị giá": value_by_item
})
item_summary_display = item_summary.copy()
item_summary_display["Tổng sản lượng"] = (
    item_summary_display["Tổng sản lượng"]
    .map(lambda x: f"{x:,.0f} nghìn tấn")
)
item_summary_display["Tổng trị giá"] = (
    item_summary_display["Tổng trị giá"]
    .map(lambda x: f"{x:,.0f} nghìn USD")
)
print(item_summary_display)

                               Tổng sản lượng          Tổng trị giá
Tên hàng
Cao su                   16,556,849 nghìn tấn  25,262,095 nghìn USD
Chè                       1,223,801 nghìn tấn   2,057,386 nghìn USD
Cà phê                   14,563,615 nghìn tấn  38,548,474 nghìn USD
Gạo                      63,120,649 nghìn tấn  32,808,494 nghìn USD
Hạt tiêu                  2,267,821 nghìn tấn   9,046,165 nghìn USD
Hạt điều                  4,930,587 nghìn tấn  33,323,826 nghìn USD
Rau quả                           0 nghìn tấn  42,562,263 nghìn USD
Sắn và sản phẩm của sắn  23,468,899 nghìn tấn  10,287,531 nghìn USD
Thủy sản                          0 nghìn tấn  84,206,451 nghìn USD
Xơ, sợi dệt các loại     14,304,006 nghìn tấn  38,936,175 nghìn USD

In [195]:
# Tỷ trọng trị giá 
item_summary_display["Tỷ trọng trị giá (%)"] = (
    item_summary["Tổng trị giá"]
    / item_summary["Tổng trị giá"].sum()
    * 100
).round(2)
display(item_summary_display)

,Tổng sản lượng,Tổng trị giá,Tỷ trọng trị giá (%)
Tên hàng,,,
Cao su,"16,556,849 nghìn tấn","25,262,095 nghìn USD",7.97
Chè,"1,223,801 nghìn tấn","2,057,386 nghìn USD",0.65
Cà phê,"14,563,615 nghìn tấn","38,548,474 nghìn USD",12.16
Gạo,"63,120,649 nghìn tấn","32,808,494 nghìn USD",10.35
Hạt tiêu,"2,267,821 nghìn tấn","9,046,165 nghìn USD",2.85
Hạt điều,"4,930,587 nghìn tấn","33,323,826 nghìn USD",10.51
Rau quả,0 nghìn tấn,"42,562,263 nghìn USD",13.42
Sắn và sản phẩm của sắn,"23,468,899 nghìn tấn","10,287,531 nghìn USD",3.24
Thủy sản,0 nghìn tấn,"84,206,451 nghìn USD",26.56
"Xơ, sợi dệt các loại","14,304,006 nghìn tấn","38,936,175 nghìn USD",12.28

In [196]:
# Mặt hàng thấp nhất, cao nhất 
print(
    "Sản lượng cao nhất:",
    quantity_by_item.idxmax()
)
print(
    "Trị giá cao nhất:",
    value_by_item.idxmax()
)
# Sản lượng thấp nhất
print("Sản lượng thấp nhất:")

lowest_quantity = quantity_by_item.sort_values().head(2)

for item, value in lowest_quantity.items():
    print(f"{item}")

print(
    "Trị giá thấp nhất:",
    value_by_item.idxmin()
)

Sản lượng cao nhất: Gạo
Trị giá cao nhất: Thủy sản
Sản lượng thấp nhất:
Thủy sản
Rau quả
Trị giá thấp nhất: Chè

## 7. Phân tích theo tháng

Phân tích sự biến động của lượng và trị giá xuất khẩu theo từng tháng
trong giai đoạn 2017–2025.

Mục tiêu:
- Xác định tháng có lượng xuất khẩu cao nhất và thấp nhất.
- Xác định tháng có trị giá xuất khẩu cao nhất và thấp nhất.
- Quan sát xu hướng biến động theo tháng.
- Xem xét khả năng xuất hiện tính mùa vụ trong hoạt động xuất khẩu.

In [197]:
# Tổng sản lượng theo tháng 
monthly_quantity = {}

for month in range(1, 13):
    col = f"Tháng {month}_Lượng"
    
    if col in df.columns:
        monthly_quantity[month] = df[col].sum()
monthly_quantity = pd.Series(monthly_quantity)
print(
    monthly_quantity.map(
        lambda x: f"{x:,.0f} tấn"
    )
)

1     11,144,362 tấn
2      9,997,987 tấn
3     14,091,238 tấn
4     12,808,707 tấn
5     12,424,947 tấn
6     10,798,287 tấn
7     11,433,718 tấn
8     12,595,376 tấn
9     10,546,397 tấn
10    10,899,299 tấn
11    11,233,053 tấn
12    12,462,856 tấn
dtype: str

In [198]:
# Tổng trị giá theo tháng 
monthly_value = {}

for month in range(1, 13):
    col = f"Tháng {month}_Trị giá"
    
    if col in df.columns:
        monthly_value[month] = df[col].sum()
monthly_value = pd.Series(monthly_value)
print(
    monthly_value.map(
        lambda x: f"{x:,.0f} nghìn USD"
    )
)

1     23,651,440 nghìn USD
2     19,820,204 nghìn USD
3     27,866,957 nghìn USD
4     26,910,199 nghìn USD
5     27,625,627 nghìn USD
6     26,782,078 nghìn USD
7     26,870,994 nghìn USD
8     28,305,817 nghìn USD
9     26,390,972 nghìn USD
10    27,305,295 nghìn USD
11    26,712,358 nghìn USD
12    28,796,917 nghìn USD
dtype: str

In [199]:
# Tháng cao nhất và thấp nhất ở sản lượng và giá trị 
print(
    "Tháng có tổng sản lượng cao nhất: Tháng",
    monthly_quantity.idxmax()
)

print(
    "Tháng có tổng sản lượng thấp nhất: Tháng",
    monthly_quantity.idxmin()
)

print(
    "Tháng có tổng trị giá cao nhất: Tháng",
    monthly_value.idxmax()
)

print(
    "Tháng có tổng trị giá thấp nhất: Tháng",
    monthly_value.idxmin()
)

Tháng có tổng sản lượng cao nhất: Tháng 3
Tháng có tổng sản lượng thấp nhất: Tháng 2
Tháng có tổng trị giá cao nhất: Tháng 12
Tháng có tổng trị giá thấp nhất: Tháng 2

In [200]:
# Tạo bảng văns tắt 
monthly_summary = pd.DataFrame({
    "Tổng sản lượng (tấn)": monthly_quantity,
    "Tổng trị giá (nghìn USD)": monthly_value
})
display(
    monthly_summary.style
    .format("{:,.0f}")
)

In [201]:
# Tỷ trọng từng tháng 
monthly_summary["Tỷ trọng trị giá (%)"] = (
    monthly_summary["Tổng trị giá (nghìn USD)"]
    / monthly_summary["Tổng trị giá (nghìn USD)"].sum()
    * 100
).round(2)
display(
    monthly_summary.style.format({
        "Tổng sản lượng (tấn)": "{:,.0f}",
        "Tổng trị giá (nghìn USD)": "{:,.0f}",
        "Tỷ trọng trị giá (%)": "{:.2f}"
    })
)

## 8. Phân tích mối quan hệ giữa sản lượng và trị giá

Phân tích mối quan hệ giữa tổng sản lượng và tổng trị giá xuất khẩu
của các mặt hàng trong giai đoạn 2017–2025.

Mục tiêu:
- Xem xét mức độ tương quan giữa sản lượng và trị giá.
- Xác định liệu các mặt hàng có sản lượng cao có đồng thời có trị giá cao hay không.
- Làm cơ sở cho việc trực quan hóa mối quan hệ giữa hai biến.

In [202]:
# Tổng sản lượng và trị giá
df["Tổng Sản lượng"] = df[quantity_cols].sum(axis=1) 
df["Tổng Trị giá"] = df[value_cols].sum(axis=1)

In [203]:
# Tính hệ số tương quan giửa sản lượng và trị giá
corralation = df[["Tổng Sản lượng", "Tổng Trị giá"]].corr()
display(corralation)

                Tổng Sản lượng  Tổng Trị giá
Tổng Sản lượng         1.00000      -0.07016
Tổng Trị giá          -0.07016       1.00000

In [204]:
# Tương quan giữa các mặt hàng 
item_corr = {}
for item, group in df.groupby("Tên hàng"):
    item_corr[item] = group["Tổng Sản lượng"].corr(group["Tổng Trị giá"])
item_corr = pd.Series(item_corr).sort_values(ascending=False)
item_corr = (
    item_corr
    .rename("Hệ số tương quan")
    .reset_index()
    .rename(columns={"index": "Tên hàng"})
)
display(
    item_corr
    .style.format({"Hệ số tương quan:": "{:.2f}" }, na_rep="NaN")
)

/home/a356/.local/lib/python3.14/site-packages/numpy/lib/_function_base_impl.py:3036: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/home/a356/.local/lib/python3.14/site-packages/numpy/lib/_function_base_impl.py:3037: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]

# Note 
Thủy sản và Rau quả có hệ số tương quan là Nan vì ở hai mặt hàng này không tính có sản lượng từ Data gốc vì vậy tương quan giữa giá trị và tương quan sản lượng là nan

## 9. Phát hiện dữ liệu bất thường

Kiểm tra các giá trị bất thường trong dữ liệu sản lượng và trị giá
xuất khẩu nhằm phát hiện những quan sát có giá trị quá lớn hoặc quá nhỏ
so với phần lớn dữ liệu.

Mục tiêu:
- Phát hiện các giá trị có khả năng là bất thường.
- Xác định các mặt hàng hoặc năm có giá trị khác biệt đáng kể.
- Kiểm tra nguyên nhân trước khi quyết định có xử lý hay không.

In [205]:
# Thống kê dữ liệu 
numeric_col = ["Tổng Sản lượng", "Tổng Trị giá"]
display(df[numeric_col].describe())

       Tổng Sản lượng  Tổng Trị giá
count    9.000000e+01  9.000000e+01
mean     1.560403e+06  3.522654e+06
std      2.086899e+06  2.658863e+06
min      0.000000e+00  2.082000e+05
25%      1.354610e+05  1.277751e+06
50%      6.839715e+05  3.302329e+06
75%      1.903774e+06  4.296508e+06
max      9.034164e+06  1.128578e+07

In [206]:
# Sử dụng phương pháp IRQ để xác định outlier 
Q1 = df[numeric_col].quantile(0.25)
Q3 = df[numeric_col].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

In [207]:
# Tìm dòng outlier
outlier_mask = (
    (df[numeric_col] < lower_bound) |
    (df[numeric_col] > upper_bound)
).any(axis=1)

outliers = df.loc[
    outlier_mask,
    ["Tên hàng", "Year"] + numeric_col
]

display(outliers)

    Tên hàng  Year  Tổng Sản lượng  Tổng Trị giá
6        Gạo  2017       5818598.0  2.633479e+06
16       Gạo  2018       6114934.0  3.063663e+06
26       Gạo  2019       6366469.0  2.805354e+06
36       Gạo  2020       6249074.0  3.120144e+06
40  Thủy sản  2021             0.0  8.886175e+06
46       Gạo  2021       6237311.0  3.285629e+06
50  Thủy sản  2022             0.0  1.092344e+07
56       Gạo  2022       7105734.0  3.454765e+06
60  Thủy sản  2023             0.0  8.971158e+06
66       Gạo  2023       8131527.0  4.675696e+06
70  Thủy sản  2024             0.0  1.004002e+07
76       Gạo  2024       9034164.0  5.666121e+06
80  Thủy sản  2025             0.0  1.128578e+07
83    Cà phê  2025       1592288.0  8.923706e+06
86       Gạo  2025       8062838.0  4.103645e+06

In [208]:
print("Số dòng bất thường:", outliers.shape[0])

Số dòng bất thường: 15

In [209]:
# Nhóm bất thường 
outlier_by_item = (
    outliers["Tên hàng"]
    .value_counts()
)

display(outlier_by_item)

Tên hàng
Gạo         9
Thủy sản    5
Cà phê      1
Name: count, dtype: int64

### Nhận xét

Các giá trị bất thường được xác định dựa trên phương pháp IQR.
Các quan sát bất thường chưa được loại bỏ mà được giữ lại để kiểm tra
nguyên nhân và đối chiếu với dữ liệu nguồn trước khi thực hiện các bước
xử lý tiếp theo.

# 10. Tổng hợp kết quả EDA

Qua quá trình khám phá và phân tích dữ liệu xuất khẩu nông sản
giai đoạn 2017–2025, có thể rút ra một số kết quả chính về quy mô,
cơ cấu mặt hàng, xu hướng theo thời gian và mối quan hệ giữa sản lượng
và trị giá xuất khẩu.

### 10.1 Đặc điểm dữ liệu

- Dữ liệu gồm các mặt hàng nông sản được lựa chọn trong giai đoạn 2017–2025.
- Dữ liệu đã được chuẩn hóa về tên mặt hàng, tên cột và đơn vị.
- Đơn vị sản lượng được chuẩn hóa về tấn.
- Trị giá được thống nhất theo nghìn USD.

### 10.2 Xu hướng theo năm

- Tổng sản lượng và tổng trị giá có sự biến động qua các năm.
- Xác định năm có tổng sản lượng cao nhất và thấp nhất.
- Xác định năm có tổng trị giá cao nhất và thấp nhất.

### 10.3 Đặc điểm theo mặt hàng

- Các mặt hàng có sự khác biệt đáng kể về sản lượng và trị giá.
- Xác định các mặt hàng có sản lượng lớn nhất.
- Xác định các mặt hàng có trị giá xuất khẩu lớn nhất.
- So sánh tỷ trọng trị giá giữa các mặt hàng.

### 10.4 Xu hướng theo tháng

- Tổng sản lượng và trị giá có sự biến động giữa các tháng.
- Xác định các tháng có sản lượng và trị giá cao nhất/thấp nhất.
- Kiểm tra khả năng xuất hiện tính mùa vụ.

### 10.5 Mối quan hệ giữa sản lượng và trị giá

- Phân tích hệ số tương quan giữa sản lượng và trị giá.
- Một số mặt hàng có tương quan dương mạnh, trong khi một số mặt hàng
  có tương quan yếu hoặc âm.
- Các kết quả tương quan cần được kết hợp với biểu đồ và đặc điểm từng
  mặt hàng để đưa ra nhận xét phù hợp.

### 10.6 Dữ liệu bất thường và dữ liệu khuyết

- Một số giá trị bất thường được phát hiện bằng phương pháp IQR.
- Các giá trị bất thường chưa được loại bỏ nếu chưa xác định là lỗi dữ liệu.
- Các giá trị khuyết cần được đối chiếu với dữ liệu nguồn trước khi quyết định
  phương pháp xử lý.

In [214]:
eda_summary = pd.DataFrame({
    "Chỉ tiêu": [
        "Năm có sản lượng cao nhất",
        "Năm có sản lượng thấp nhất",
        "Năm có trị giá cao nhất",
        "Năm có trị giá thấp nhất",
        "Mặt hàng có sản lượng cao nhất",
        "Mặt hàng có sản lượng thấp nhất",
        "Mặt hàng có trị giá cao nhất",
        "Mặt hàng có trị giá thấp nhất"
    ],
    "Kết quả": [
        quantity_by_year.idxmax(),
        quantity_by_year.idxmin(),
        value_by_year.idxmax(),
        value_by_year.idxmin(),
        quantity_by_item.idxmax(),
        ", ".join(
            quantity_by_item[
                quantity_by_item == quantity_by_item.min()
            ].index
        ),
        value_by_item.idxmax(),
        value_by_item.idxmin()
    ]
})

display(eda_summary)

                          Chỉ tiêu            Kết quả
0        Năm có sản lượng cao nhất               2025
1       Năm có sản lượng thấp nhất               2017
2          Năm có trị giá cao nhất               2025
3         Năm có trị giá thấp nhất               2020
4   Mặt hàng có sản lượng cao nhất                Gạo
5  Mặt hàng có sản lượng thấp nhất  Rau quả, Thủy sản
6     Mặt hàng có trị giá cao nhất           Thủy sản
7    Mặt hàng có trị giá thấp nhất                Chè